language: go
install:
- go get github.com/gorilla/mux
go:
- master

script:
  - go build teapot.go

deploy:
  provider: releases
  api_key:
    secure: HiIH6nJPCY0UsWZ70qvamnCSz6Fys33x/BsjOdRK/urpNV2IUVzGQeT12EQgHeos0BwzpwnrEo5jahUspzoBc6+Lv9jLphWtfSNhgv48tlVWhx27pk9opKSL30rigY+7n/d71Jyenq3tvxfwjR87y4HT1tm/yrI34z0SxvQsf1un1KlGdOYpStv0fLwbWJkDML/jlcj/zlzhpi+QJARwQCtJ07qlqdb29Q5nD5f9yHxMul5V3XQTAE4Go4fmezhNw3ohOg7ru0vYi+XSr0EmItHaUceqfo8kEiAH+oDsrmYVek1iUz/Pvi+JH92kP5Z+csvHKpht6nzwDA8e/pzijwrkIWjXHj++GkNoyvB+Tvf5Y3FXNgx75cAWYBhE6W7HcyKL7bTWqJ/0/uYRgBgNphFr3IUk1JtydMFwVg19KLF6wpgKC7pMRyFQMYEIgsekw6VdBjR0N+lSaSmlmlU16NN3JdDSJ/f9HCuYT19U+PpmxmGdMqAcuzF2KH7Ly/o7ztEPqgSolaux9uBAl9pYM2xSSpYM3h7thgfRTMu6RQomMqugr84ACZR8bwPbe2a/pQrNYJZnnu35QqTRJttvdklZWboNzIOoPuBGYRgCd7nHtxQHL0WAaWp8QcB9/J01ykPemICT0ljlOotRy23m36vDQmF0K1LC4d8iAnoB0tI=
  file: teapot
  on:
    repo: planchao/teapot
